title: Embodied Question Answering
email: abhshkdz@gatech.edu
description: Moving towards AI agents that can navigate in virtual environments and answer natural language questions
  ---
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://embodiedqa.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-110470966-1
