title: Visual Learning and Embodied Agents in Simulation Environments
email: samyak@gatech.edu
description: ECCV 2018 (Munich, Germany)
  ---
baseurl: "/eccv-vlease-workshop" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-110470966-1
